name: Deploy develop
on:
  push:
    branches:
      - develop
jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-18.04
    strategy: # Node version은 12 버전을 이용한다.
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2 # Initialize Node.js
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        # Install project dependencies, test and build

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [14.x] # 위의 buildAndTest가 실행되고 진행된다.

    steps:
      - uses: actions/checkout@v2


      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        # Install project dependencies and build
      - name: Install dependencies
        run: npm install

      - name: install nest
        run: npm install -g @nestjs/cli

      - name: Run build
        run: npm run build

      - name: run postbuild
        run: zip -r deploy.zip . -x '*.git*' './src/*' './node_modules/*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: jesusFingers-nestjs-server
          environment_name: jesujesusFingers-nestjs-server
          version_label: 12345678
          region: ${{ secrets.AWS_REGION }}
          use_existing_version_if_available: true
          deployment_package: deploy.zip
